### PR TITLE
Add Contao 3 comaptibility

### PR DESCRIPTION
**Pull request by cliffparnitzky**
Seems, this is the only extension, which supports automatisch switching to mobile page trees.

Please add Contao 3 compatibility.

Only adding autoload files is not enough, e.g. access to `Environment` is now static.

### CODE REVIEW

**Comment by cliffparnitzky** [comment]
Added my changes as pull request.

Usage of select field in `tl_article` is not clear :-/

**Comment by aschempp** [comment]
Unfortunately, using the static access removes compatibility with Contao 2.11. The static methods are not necessary in Contao 3, could you remove them again? Also, please set all flags to `false` in autoload.ini

**Comment by cliffparnitzky** [comment]
Arg ... now i understand the configuring. Didn't found the media query, because i forgot to setup the desktop page equivalent.

Please add a short instruction note to the ER description.

Now the pull contains the missing legend translation in tl_page and die autoload files for contao 3.

**Comment by aschempp** [comment]
Would you be able to write the short introduction? Its always better from a user, and quite a while since I used it ;-)

Pull request looks good! I'll merge it as soon as I can publish the changes.

**Comment by cliffparnitzky** [comment]
Thats great, thank you.

Here are the notes (html prepared for ER):

## DEUTSCH

```
<h3>Konfiguration</h3>
<ul>
<li>In der ROOT Seite des mobilen Seitenbaums die Option "Mobiler Seitenbaum" aktivieren.</li>
<li>Dann "Desktop Seitenbaum", "Geräte-Erkennung" und ggf. "Media Query" festlegen.</li>
<li>Nun den einzelnen Seiten des mobilen Baums eine entsprechende Desktop-Seite zuweisen (ein solche Verknüpfung muss wenigstens zwischen den beiden Startseiten der Bäume existieren).</li>
<li>Zum Schluss ein Modul von Typ "Gerätwechsler" anlegen und z.B. im mobilen Seitenlayout einfügen.</li>
</ul>
<h3>Hinweis zum Cookie</h3>
<ul>
<li>Das Cookie "useDesktop" wird gesetzt, wenn von der mobilen Seiten via o.g. Modul auf die Desktop Variante gewechselt wird.</li>
<li>Ist das Cookie gesetzt, bleibt der Benutzer auf der Desktop Seite.</li>
<li>Die Ablaufzeit ist so eingestellt, dass das Cookie am Ende der Session (wenn der Browser geschlossen wird) verfällt.</li>
<li>Bei einem erneuten Besuch der Webseite gelangt der Benutzer dann wieder auf die mobile Variante.</li>
</ul>
```

## ENGLISH

```
<h3>Configuration</h3>
<ul>
<li>Go to the ROOT page of the mobile page tree and select the option "Mobile Site".</li>
<li>Then define "Desktop Site", "Device detection" and if applicable "Media query".</li>
<li>Now assign each page of the mobile tree to its a corresponding desktop page (there musst be at least one link between the two start pages of the trees).</li>
<li>Finally create a module of type "Change Device" and add it to the mobile page layout.</li>
</ul>
<h3>Note for the cookie</h3>
<ul>
<li>The cookie "useDesktop" is set if the user switches from the mobile page to the desktop version via the module above.</li>
<li>If the cookie is set, the user remains on the desktop page.</li>
<li>The cookie will expire at the end of the session (when the browser is closed).</li>
<li>On a return visit to the website, the user then reaches the mobile version again.</li>
</ul>
```

**Comment by aschempp** [comment]
Perfect, thanks a lot! We'll get that out as soon as possible :-)

**Comment by DevPoint** [comment]
I currently use changedevice with cliffs pull request included.
I chosed to work with the server based agent detection.
I had the problem, that the variable $strUrl contained an invalid URL. It contained the domain name twice.
After debugging, I discovered that generateFrontendUrl already delivers a complete Url with http://domainname included. After patching the source code to avoid this behaviour, everything runs as suspected. Have I missed anything or is generateFrontendUrl in Contao 3.x behaving different to earlier versions?

**Pull request closed without merging**
